# Generated by Django 4.2.11 on 2024-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_creators', '0002_add_org_support_for_course_creators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partner_logos/')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
